name: rendezvous_app # You can adjust this if you prefer a different package name
description: "A Flutter application for Rendezvous assessment."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  # Requirement: Flutter 3.24 or higher
  sdk: '>=3.4.0 <4.0.0' # Allows Flutter 3.24.x and future minor versions up to 4.0.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Core & Utility Packages
  http: ^1.2.1 # Requirement: For API requests
  provider: ^6.1.2 # Requirement: For state management
  connectivity_plus: ^6.0.3 # Used in NetworkInfo
  shared_preferences: ^2.2.3 # Used in AppState for persistence
  dartz: ^0.10.1 # Used for Functional Programming (Either) in domain/data layers
  intl: ^0.19.0 # Used for date formatting (DatePicker)
  path: ^1.9.0 # Used for handling file paths (video upload)
  http_parser: ^4.0.2 # Used for multipart request content type (video upload)

  # UI & Feature Packages
  image_picker: ^1.1.2 # For picking video from gallery
  video_player: ^2.8.6 # For validating video duration

  # Add other dependencies here if needed
  # Example: cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # Ensure 'assets:' is indented under 'flutter:'
  assets:
    # Ensure list items under 'assets:' are indented further
    # Assuming you might have logo or other images in assets/images/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # Ensure 'fonts:' is indented under 'flutter:' (same level as 'assets:')
  fonts:
    # Ensure list items ('-') under 'fonts:' are indented further
    - family: Inter # Font specified in theme.dart and requirements
      # Ensure keys ('family', 'fonts') are indented under the list item '-'
      fonts:
        # Ensure list items ('-') under the inner 'fonts:' key are indented further
        - asset: assets/fonts/Inter-Regular.ttf
        # Add other weights/styles if you have them, e.g.:
        # - asset: assets/fonts/Inter-Bold.ttf
        #   weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

